import {
    IconCash,
    IconBuilding,
    IconBriefcase,
    IconGift,
    IconPigMoney,
    IconCoin,
    IconReceipt,
    IconShoppingCart,
    IconHome,
    IconCar,
    IconPlane,
    IconApple,
    IconShirt,
    IconDeviceTv,
    IconHeartbeat,
    IconSchool,
    IconBus,
    IconDeviceGamepad2,
    IconPhone,
    IconDog,
    IconPalette,
    IconMoodSmile,
  } from '@tabler/icons-react';
  
  export const incomeIconOptions = [
    { value: 'IconCash', label: 'Salary', icon: IconCash },
    { value: 'IconBuilding', label: 'Rental Income', icon: IconBuilding },
    { value: 'IconBriefcase', label: 'Business Income', icon: IconBriefcase },
    { value: 'IconGift', label: 'Gifts', icon: IconGift },
    { value: 'IconPigMoney', label: 'Savings Interest', icon: IconPigMoney },
    { value: 'IconCoin', label: 'Investments', icon: IconCoin },
  ];
  
  export const expenseIconOptions = [
    { value: 'IconReceipt', label: 'Bills', icon: IconReceipt },
    { value: 'IconShoppingCart', label: 'Shopping', icon: IconShoppingCart },
    { value: 'IconHome', label: 'Housing', icon: IconHome },
    { value: 'IconCar', label: 'Transportation', icon: IconCar },
    { value: 'IconPlane', label: 'Travel', icon: IconPlane },
    { value: 'IconApple', label: 'Groceries', icon: IconApple },
    { value: 'IconShirt', label: 'Clothing', icon: IconShirt },
    { value: 'IconDeviceTv', label: 'Entertainment', icon: IconDeviceTv },
    { value: 'IconHeartbeat', label: 'Healthcare', icon: IconHeartbeat },
    { value: 'IconSchool', label: 'Education', icon: IconSchool },
    { value: 'IconBus', label: 'Public Transport', icon: IconBus },
    { value: 'IconDeviceGamepad2', label: 'Gaming', icon: IconDeviceGamepad2 },
    { value: 'IconPhone', label: 'Communication', icon: IconPhone },
    { value: 'IconDog', label: 'Pets', icon: IconDog },
    { value: 'IconPalette', label: 'Hobbies', icon: IconPalette },
    { value: 'IconMoodSmile', label: 'Personal Care', icon: IconMoodSmile },
  ];